In [11]:
import numpy as np
import pandas as pd

df = pd.read_excel('subnational-debt-OECD.xlsx', sheetname="Sheet1")
df.describe()

,Subnational Debt,Population,Area,Debt per km squared,Debt per person,Population Density,Share of GDP,Share of Public Debt,GDP,GDP Growth
count,32.000000,34.000000,3.400000e+01,3.200000e+01,32.000000,34.000000,31.000000,31.000000,34.000000,34.000000
mean,352.631250,37848.323529,1.013720e+06,7.828084e+05,5869.425000,143.801471,13.691691,16.834508,1530.967647,3.005882
std,953.053084,60498.176547,2.447630e+06,1.178953e+06,6185.708149,139.438475,13.471881,15.145991,3143.551064,4.335473
min,1.400000,327.000000,2.586000e+03,1.795640e+04,172.300000,3.070000,0.700933,0.627694,15.800000,-0.200000
25%,7.100000,5508.000000,5.387550e+04,9.587418e+04,1306.350000,31.435000,3.702247,7.212075,280.300000,1.425000
50%,53.450000,10726.000000,1.866645e+05,2.140407e+05,4219.750000,103.035000,11.324195,11.388120,448.000000,2.300000
75%,225.300000,49434.000000,3.988875e+05,7.328570e+05,8797.200000,213.022500,17.422367,23.761039,1718.500000,3.175000
max,5126.800000,319173.000000,9.161923e+06,4.664686e+06,28638.200000,506.970000,63.542137,59.039130,18036.600000,26.300000